#!/bin/sh

set -e # Exit immediately if a command exits with a non-zero status.

# --- Configuration ---
USERNAME="hotaru"

# --- Main Script ---

echo "🚀 Starting dotfiles installation..."

# 1. Build the Home Manager configuration
echo "Building Home Manager configuration..."
nix build .#home-manager

# 2. Activate the configuration
echo "Activating Home Manager configuration..."
./result/activate

# 3. Set up xremap permissions and service
echo "Setting up xremap..."

# Check if running as root
if [ "$(id -u)" -ne 0 ]; then
  echo "Sudo privileges are required to set up udev rules and manage services."
  # Re-run the script with sudo, but only for the setup part
  sudo "$0" "--setup-xremap"
  exit 0
fi

# This part of the script runs only when called with --setup-xremap
if [ "$1" = "--setup-xremap" ]; then
  echo "Configuring udev rules for xremap..."
  # Add user to the input group if not already a member
  if ! groups "$USERNAME" | grep -q '\binput\b'; then
    echo "Adding user '$USERNAME' to the 'input' group..."
    usermod -aG input "$USERNAME"
    echo "You may need to log out and log back in for the group change to take effect."
  fi

  # Create udev rules for device access
  cat > /etc/udev/rules.d/99-input.rules <<EOF
# Rule for xremap to access input devices
KERNEL=="event*", GROUP="input", MODE="0660"
KERNEL=="uinput", GROUP="input", MODE="0660"
EOF

  echo "Reloading udev rules..."
  udevadm control --reload-rules
  udevadm trigger

  echo "Linking and enabling xremap systemd service..."
  # The service file is generated by home-manager in the user's home directory
  SERVICE_PATH="/home/$USERNAME/.config/systemd/user/xremap.service"
  if [ -f "$SERVICE_PATH" ]; then
    # Run systemctl commands as the user
    sudo -u "$USERNAME" XDG_RUNTIME_DIR=/run/user/$(id -u $USERNAME) systemctl --user daemon-reload
    sudo -u "$USERNAME" XDG_RUNTIME_DIR=/run/user/$(id -u $USERNAME) systemctl --user enable --now xremap
    echo "xremap service has been enabled and started."
  else
    echo "Warning: xremap service file not found at $SERVICE_PATH" >&2
    echo "Please ensure home-manager has been activated correctly." >&2
  fi

  echo "✅ xremap setup complete."
  exit 0
fi

echo "✅ Dotfiles installation complete!"