{ config, pkgs, unstable, lib, ... }:
let
  target = "wayland-session@Hyprland.target";
  tools = import ./packages.nix { inherit pkgs unstable; };
  inherit (tools) dms launcher wallpaper keyboard clipboard clipboardMenu locker cheatsheet;
  defaults = pkgs.writeText "dotfiles-dms-defaults.json" (builtins.toJSON {
    settings = {
      fontFamily = "Noto Sans CJK JP";
      monoFontFamily = "JetBrainsMono Nerd Font";
      cornerRadius = 14;
      showWeather = false;
      showClipboard = false;
      clipboardClickToPaste = false;
      clipboardEnterToPaste = false;
      # DMS's idle timers are adjustable in Settings > Power & Sleep.
      acLockTimeout = 300;
      batteryLockTimeout = 300;
      acMonitorTimeout = 600;
      batteryMonitorTimeout = 600;
      acSuspendTimeout = 0;
      batterySuspendTimeout = 0;
      fadeToLockEnabled = false;
      # hypridle holds the suspend inhibitor until hyprlock is ready.
      lockBeforeSuspend = false;
      loginctlLockIntegration = true;
      # Do not let a shell theme overwrite managed Fcitx/GTK/app settings.
      runDmsMatugenTemplates = false;
    };
    policy = {
      customPowerActionLock = "${locker}/bin/desktop-lock";
      customPowerActionLogout = "${pkgs.uwsm}/bin/uwsm stop";
      launchPrefix = "${pkgs.uwsm}/bin/uwsm app --";
    };
    session = {
      wallpaperPath = "${config.home.homeDirectory}/.local/share/backgrounds/nix-nineish-mocha-alt.png";
      isLightMode = false;
      terminalOverride = "kitty";
    };
  });
  configure = pkgs.writeShellApplication {
    name = "desktop-dms-config";
    runtimeInputs = [ pkgs.python3 ];
    text = ''exec python3 ${./seed_dms.py} ${defaults}'';
  };
  session = pkgs.writeShellApplication {
    name = "desktop-dms-session";
    runtimeInputs = [ dms unstable.quickshell pkgs.coreutils pkgs.bash pkgs.glib ];
    text = ''exec dms run --session'';
  };
  commands = {
    terminal = "${pkgs.uwsm}/bin/uwsm app -- ${pkgs.kitty}/bin/kitty";
    fileManager = "${pkgs.uwsm}/bin/uwsm app -- ${pkgs.nautilus}/bin/nautilus";
    launcher = "${launcher}/bin/desktop-launcher";
    dms = "${dms}/bin/dms";
    cheatsheet = "${dms}/bin/dms ipc call keybinds toggle hyprland";
    keyboard = "${keyboard}/bin/keyboard-profile toggle";
    clipboard = "${clipboardMenu}/bin/desktop-clipboard-menu";
    clipboardPrivacy = "${clipboard}/bin/desktop-clipboard toggle";
    clipboardClear = "${clipboard}/bin/desktop-clipboard clear";
    lock = "${locker}/bin/desktop-lock";
    logout = "${pkgs.uwsm}/bin/uwsm stop";
    restartShell = "${pkgs.systemd}/bin/systemctl --user restart dms.service";
  };
  luaString = value: builtins.toJSON value;
  entry = name: exec: icon: {
    inherit name exec icon;
    terminal = false;
    categories = [ "Settings" "Utility" ];
    settings.OnlyShowIn = "Hyprland;";
  };
in {
  home.packages = [ launcher configure pkgs.brightnessctl ];
  home.file.".local/share/backgrounds/nix-nineish-mocha-alt.png".source = wallpaper;
  home.activation.seedDms = lib.hm.dag.entryAfter [ "writeBoundary" ] ''
    run ${configure}/bin/desktop-dms-config
  '';
  xdg.configFile = {
    "hypr/hyprland.lua".source = ./hypr/hyprland.lua;
    "hypr/input.lua".source = ./hypr/input.lua;
    "hypr/appearance.lua".source = ./hypr/appearance.lua;
    "hypr/binds.lua".source = ./hypr/binds.lua;
    "hypr/commands.lua".text = ''
      -- Executable paths generated by Home Manager; no shell startup PATH needed.
      return {
        ${lib.concatStringsSep "\n  " (lib.mapAttrsToList (name: value: ''${name} = ${luaString value},'') commands)}
      }
    '';
    # Only this security policy is read-only. Normal settings remain writable.
    # DMS's built-in persistent history must not duplicate the private recorder.
    "DankMaterialShell/clsettings.json".text = builtins.toJSON {
      disabled = true;
      maxHistory = 100;
      maxEntrySize = 65536;
      maxPinned = 0;
    };
  };
  systemd.user.services.dms = {
    Unit = {
      Description = "DankMaterialShell desktop (Hyprland only)";
      After = [ "graphical-session.target" ];
      PartOf = [ target ];
    };
    Service = {
      ExecStartPre = "${configure}/bin/desktop-dms-config";
      ExecStart = "${session}/bin/desktop-dms-session";
      Restart = "on-failure";
      RestartSec = 2;
      UMask = "0077";
      LimitCORE = 0;
    };
    Install.WantedBy = [ target ];
  };
  xdg.desktopEntries = {
    dotfiles-settings = entry "Settings: Desktop" "${dms}/bin/dms ipc call settings focusOrToggle" "preferences-system";
    dotfiles-displays = entry "Settings: Displays and mirroring" "${dms}/bin/dms ipc call settings focusOrToggleWith displays" "preferences-desktop-display";
    dotfiles-shortcuts = entry "Action: Hyprland shortcuts" "${dms}/bin/dms ipc call keybinds toggle hyprland" "input-keyboard";
    dotfiles-dms-restart = entry "Action: Restart desktop shell" commands.restartShell "view-refresh";
    dotfiles-zoom-web = entry "Zoom Web" "${pkgs.xdg-utils}/bin/xdg-open https://app.zoom.us/wc" "web-browser";
  };
}
