local c = require("commands")

-- Keys are XKB physical codes (evdev + 8), unaffected by typing profile.
hl.bind("SUPER + space", hl.dsp.exec_cmd(c.launcher), { description = "Apps and actions" })
hl.bind("SUPER + code:40", hl.dsp.exec_cmd(c.launcher), { description = "Apps and actions (Win+D)" })
hl.bind("SUPER + F1", hl.dsp.exec_cmd(c.cheatsheet), { description = "Shortcut cheat sheet" })
hl.bind("SUPER + F2", hl.dsp.exec_cmd(c.keyboard), { release = true, description = "QWERTY / custom Dvorak" })
hl.bind("SUPER + code:55", hl.dsp.exec_cmd(c.clipboard), { description = "Private clipboard history (Win+V)" })
hl.bind("SUPER + SHIFT + code:55", hl.dsp.exec_cmd(c.clipboardPrivacy), { description = "Pause / resume clipboard history" })
hl.bind("SUPER + CTRL + code:55", hl.dsp.exec_cmd(c.clipboardClear), { description = "Clear clipboard history" })
hl.bind("SUPER + Return", hl.dsp.exec_cmd(c.terminal), { description = "Terminal" })\nhl.bind("CTRL + ALT + T", hl.dsp.exec_cmd(c.terminal), { description = "Emergency terminal (Ctrl+Alt+T)" })
hl.bind("SUPER + code:26", hl.dsp.exec_cmd(c.fileManager), { description = "Files (Win+E)" })
hl.bind("SUPER + code:46", hl.dsp.exec_cmd(c.lock), { description = "Lock and clear clipboard (Win+L)" })
hl.bind("SUPER + code:33", hl.dsp.exec_cmd(c.dms .. " ipc call settings focusOrToggleWith displays"), { description = "Displays / mirroring (Win+P)" })
hl.bind("SUPER + code:31", hl.dsp.exec_cmd(c.dms .. " ipc call settings focusOrToggle"), { description = "Desktop settings (Win+I)" })
hl.bind("SUPER + code:38", hl.dsp.exec_cmd(c.dms .. " ipc call control-center toggle"), { description = "Quick settings (Win+A)" })
hl.bind("SUPER + code:57", hl.dsp.exec_cmd(c.dms .. " ipc call notifications toggle"), { description = "Notifications (Win+N)" })
hl.bind("SUPER + code:53", hl.dsp.exec_cmd(c.dms .. " ipc call powermenu toggle"), { description = "Power menu (Win+X)" })
hl.bind("SUPER + CTRL + F5", hl.dsp.exec_cmd(c.restartShell), { description = "Restart DMS" })

hl.bind("SUPER + SHIFT + code:24", hl.dsp.window.close(), { description = "Close window (Win+Shift+Q)" })
hl.bind("SUPER + code:41", hl.dsp.window.fullscreen({ mode = "fullscreen", action = "toggle" }), { description = "Fullscreen (Win+F)" })
hl.bind("SUPER + SHIFT + space", hl.dsp.window.float({ action = "toggle" }), { description = "Toggle floating" })
hl.bind("SUPER + SHIFT + code:58", hl.dsp.exec_cmd(c.logout), { description = "End UWSM session (Win+Shift+M)" })
hl.bind("SUPER + left", hl.dsp.focus({ direction = "l" }), { description = "Focus left" })
hl.bind("SUPER + right", hl.dsp.focus({ direction = "r" }), { description = "Focus right" })
hl.bind("SUPER + up", hl.dsp.focus({ direction = "u" }), { description = "Focus above" })
hl.bind("SUPER + down", hl.dsp.focus({ direction = "d" }), { description = "Focus below" })
hl.bind("SUPER + SHIFT + left", hl.dsp.window.move({ direction = "l" }), { description = "Move window left" })
hl.bind("SUPER + SHIFT + right", hl.dsp.window.move({ direction = "r" }), { description = "Move window right" })
hl.bind("SUPER + SHIFT + up", hl.dsp.window.move({ direction = "u" }), { description = "Move window above" })
hl.bind("SUPER + SHIFT + down", hl.dsp.window.move({ direction = "d" }), { description = "Move window below" })
hl.bind("SUPER + mouse:272", hl.dsp.window.drag(), { mouse = true, description = "Drag window" })
hl.bind("SUPER + mouse:273", hl.dsp.window.resize(), { mouse = true, description = "Resize window" })

for workspace = 1, 10 do
    local code = tostring(workspace + 9)
    hl.bind("SUPER + code:" .. code, hl.dsp.focus({ workspace = workspace }), { description = "Workspace " .. workspace })
    hl.bind("SUPER + SHIFT + code:" .. code, hl.dsp.window.move({ workspace = workspace, follow = false }), { description = "Send to workspace " .. workspace })
end

hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd(c.dms .. " ipc call audio increment 5"), { locked = true, repeating = true, description = "Volume up" })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd(c.dms .. " ipc call audio decrement 5"), { locked = true, repeating = true, description = "Volume down" })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd(c.dms .. " ipc call audio mute"), { locked = true, description = "Mute audio" })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd(c.dms .. " ipc call audio micmute"), { locked = true, description = "Mute microphone" })
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd(c.dms .. ' ipc call brightness increment 5 ""'), { locked = true, repeating = true, description = "Brightness up" })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(c.dms .. ' ipc call brightness decrement 5 ""'), { locked = true, repeating = true, description = "Brightness down" })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd(c.dms .. " ipc call mpris playPause"), { locked = true, description = "Play / pause" })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd(c.dms .. " ipc call mpris next"), { locked = true, description = "Next track" })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd(c.dms .. " ipc call mpris previous"), { locked = true, description = "Previous track" })
hl.bind("Print", hl.dsp.exec_cmd(c.dms .. " screenshot"), { description = "Screenshot region" })
