-- Hyprland 0.55+; systemd/UWSM owns startup, not exec-once hooks.
hl.config({ autogenerated = false })
hl.monitor({ output = "", mode = "preferred", position = "auto", scale = 1 })
require("input")
require("appearance")
require("binds")

-- These ordinary files are seeded once, then written by DMS's settings GUI.
-- Requiring them registers them for Hyprland's config reload tracking.
require("dms.outputs")
require("dms.layout")
require("dms.colors")
require("dms.cursor")
require("dms.windowrules")
-- Do not load DMS's default binds: they would replace private clipboard/IME keys.
